sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tMk8CZrs4gwEae3CUtn
    access-key-secret: BHfpJG1IBlrIqFGqoS3xAqOI2ihl23
    bucket-name: sky-take-out-ithdh
